services:
  fertilizer:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - '.:/app'
    ports:
      - '9713:9713'
    entrypoint: /bin/bash
    command: 
      - -c
      - |
        echo 'Starting Fertilizer...'
        trap "echo Shutting down; exit 0" SIGTERM SIGINT SIGKILL
        sleep infinity &
        wait
    stdin_open: true
    tty: true
    env_file:
      - .env
