FROM python:3.11-slim-buster

WORKDIR /app

COPY pyproject.toml docker_start ./
COPY src src

RUN apt-get update \
  && echo "----- Installing python requirements" \
  && pip install uv \
  && uv pip install -r pyproject.toml --system --all-extras \
  && uv pip install -e . --system \
  && echo "----- Preparing directories" \
  && mkdir /config /data /torrents \
  && echo "----- Cleanup" \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 9713

ENTRYPOINT ["./docker_start"]
