name: Lint and test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --trusted-host pypi.python.org -r requirements.txt
      - name: Lint with Ruff
        run: ruff check
      - name: Check formatting with Ruff
        run: ruff format --check
      - name: Test with pytest
        run: pytest
